name: 'cdk-github-action-kmzz'
description: 'Action for AWS CDK'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'red'
inputs:
  cdk_action:
    description: 'CDK Action ex: bootstrap | diff | deploy'
    required: true
    default: 'bootstrap'
  cdk_version:
    description: 'AWS CDK version'
    required: false
    default: 'latest'
