name: Github Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      - run: npx semantic-release
      - id: semantic
      - run: echo ${{ steps.semantic.outputs }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

