name: Github Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release new docker image
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} docker.io
          docker build --tag ${{secrets.DOCKER_USERNAME}}/automate-cdk-github-action-kmzz:v${{ steps.semantic.outputs.new_release_version }} .
          docker push ${{secrets.DOCKER_USERNAME}}/automate-cdk-github-action-kmzz:v${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_version }}
          